/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.us.mwm.twitter.gui;

import es.us.mwm.twitter.entities.tweets.Tweet;
import java.awt.Component;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author fcojperez
 */
public class Elemento extends javax.swing.JPanel implements ListCellRenderer<Tweet>  {

    /**
     * Creates new form NewJPanel
     */
    public Elemento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrPanelElemento = new javax.swing.JScrollPane();
        jTxtPaneTweet = new javax.swing.JTextPane();
        jLblUsuarioTweet = new javax.swing.JLabel();
        jLblAvatar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(359, 137));
        setRequestFocusEnabled(false);

        jScrPanelElemento.setViewportView(jTxtPaneTweet);

        jLblUsuarioTweet.setForeground(new java.awt.Color(0, 51, 255));
        jLblUsuarioTweet.setText("jLabel1");

        jLblAvatar.setText("Avatar");
        jLblAvatar.setMaximumSize(new java.awt.Dimension(48, 48));
        jLblAvatar.setMinimumSize(new java.awt.Dimension(48, 48));
        jLblAvatar.setPreferredSize(new java.awt.Dimension(48, 48));
        jLblAvatar.setSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrPanelElemento)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUsuarioTweet, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblUsuarioTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrPanelElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblAvatar;
    private javax.swing.JLabel jLblUsuarioTweet;
    private javax.swing.JScrollPane jScrPanelElemento;
    private javax.swing.JTextPane jTxtPaneTweet;
    // End of variables declaration//GEN-END:variables



    @Override
    public Component getListCellRendererComponent(JList<? extends Tweet> list, Tweet value, int index, boolean isSelected, boolean cellHasFocus)  {
        jTxtPaneTweet.setText(value.getText());
        jLblUsuarioTweet.setText(value.getUser().getName());
        try{    
            String iconSrc = value.getUser().getProfile_image_url();
            URL iconUrl = new URL(iconSrc);
            ImageIcon icon = new ImageIcon(iconUrl,value.getUser().getName());
            jLblAvatar.setIcon(icon);
            jLblAvatar.setText("");
        }catch(Exception ex){
            jLblAvatar.setText("Avatar: " + value.getUser().getName());
            System.err.println("Error al obtener el avater: " + ex.getMessage());
        }
        return this;
    }
}
